#!/bin/bash
npm_reg_confluence="https://confluence.atypon.com/display/PROT/How+to+access+Atypon%27s+private+packages"

function openUrl() {
    UNAME=$(uname)
    if [ "$UNAME" == "Linux" ] ; then
        xdg-open "$1"
    elif [ "$UNAME" == "Darwin" ] ; then
        open "$1"
    elif [[ "$UNAME" == CYGWIN* || "$UNAME" == MINGW* ]] ; then
        start "$1"
    fi
}


if [ -z "$skip_protypone_install" ]; then
    echo Installing protypon dep...
    npm install -g @atypon/protypon-cli
    if [ "${?}" = "1" ]; then
        printf "Error accessing atypon's private npm registry \nplease follow => \n$npm_reg_confluence \n"
        openUrl "$npm_reg_confluence"
        exit 1
    fi
fi

echo Installing typescript globally...
npm i -g ts-node typescript
husky install
if [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    chmod ug+x .husky/*
    chmod ug+x .git/hooks/*
fi
